
package org.example.creditlimitservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.keybank.creditlimitreq.CreditLimitReqType;
import org.keybank.creditlimitserviceres.CreditLimitServiceResType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditLimitService", targetNamespace = "http://www.example.org/CreditLimitService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.keybank.creditlimitreq.ObjectFactory.class,
    org.keybank.creditlimitserviceres.ObjectFactory.class
})
public interface CreditLimitService {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.keybank.creditlimitserviceres.CreditLimitServiceResType
     */
    @WebMethod(operationName = "VerifyPromoCode")
    @WebResult(name = "CreditLimitServiceRes", targetNamespace = "http://www.keybank.org/CreditLimitServiceRes", partName = "parameters")
    public CreditLimitServiceResType verifyPromoCode(
        @WebParam(name = "CreditLimitReq", targetNamespace = "http://www.keybank.org/CreditLimitReq", partName = "parameters")
        CreditLimitReqType parameters);

}
