//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.22 at 11:07:40 AM IST 
//


package com.sreenutech.scema.res;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sreenutech.scema.res package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrderRes_QNAME = new QName("http://www.sreenutech.com/scema/Res", "OrderRes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sreenutech.scema.res
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderResBean }
     * 
     */
    public OrderResBean createOrderResBean() {
        return new OrderResBean();
    }

    /**
     * Create an instance of {@link StatusBeans }
     * 
     */
    public StatusBeans createStatusBeans() {
        return new StatusBeans();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderResBean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sreenutech.com/scema/Res", name = "OrderRes")
    public JAXBElement<OrderResBean> createOrderRes(OrderResBean value) {
        return new JAXBElement<OrderResBean>(_OrderRes_QNAME, OrderResBean.class, null, value);
    }

}
