
package org.example.creditlimitservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CreditLimitOffer", targetNamespace = "http://www.example.org/CreditLimitService/", wsdlLocation = "file:/C:/Users/SUMAN/Downloads/sreenu%20rest/Rest/CreditLimitServiceSOAP-jar/src/main/resources/CreditLimitService.wsdl")
public class CreditLimitOffer
    extends Service
{

    private final static URL CREDITLIMITOFFER_WSDL_LOCATION;
    private final static WebServiceException CREDITLIMITOFFER_EXCEPTION;
    private final static QName CREDITLIMITOFFER_QNAME = new QName("http://www.example.org/CreditLimitService/", "CreditLimitOffer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/SUMAN/Downloads/sreenu%20rest/Rest/CreditLimitServiceSOAP-jar/src/main/resources/CreditLimitService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREDITLIMITOFFER_WSDL_LOCATION = url;
        CREDITLIMITOFFER_EXCEPTION = e;
    }

    public CreditLimitOffer() {
        super(__getWsdlLocation(), CREDITLIMITOFFER_QNAME);
    }

    public CreditLimitOffer(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREDITLIMITOFFER_QNAME, features);
    }

    public CreditLimitOffer(URL wsdlLocation) {
        super(wsdlLocation, CREDITLIMITOFFER_QNAME);
    }

    public CreditLimitOffer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREDITLIMITOFFER_QNAME, features);
    }

    public CreditLimitOffer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditLimitOffer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreditLimitService
     */
    @WebEndpoint(name = "CreditLimitServicePort")
    public CreditLimitService getCreditLimitServicePort() {
        return super.getPort(new QName("http://www.example.org/CreditLimitService/", "CreditLimitServicePort"), CreditLimitService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditLimitService
     */
    @WebEndpoint(name = "CreditLimitServicePort")
    public CreditLimitService getCreditLimitServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/CreditLimitService/", "CreditLimitServicePort"), CreditLimitService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREDITLIMITOFFER_EXCEPTION!= null) {
            throw CREDITLIMITOFFER_EXCEPTION;
        }
        return CREDITLIMITOFFER_WSDL_LOCATION;
    }

}
